#!/usr/bin/env python
"""Generate config_full_image.yml from config.yml, changing only work_dir.

The full-image run should normally just use config.yml with a --work-dir
override. This generator exists so config_full_image.yml is never hand-edited
and can't silently drift from config.yml. It copies config.yml verbatim and
only rewrites the data.work_dir line.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

HEADER = (
    "# GENERATED by scripts/make_full_image_config.py from config.yml.\n"
    "# Do not edit by hand -- only work_dir differs from config.yml.\n"
    "# Prefer: run_candidate_pilot.py --config config.yml --work-dir <dir>\n"
)


def rewrite_work_dir(text: str, work_dir: str) -> str:
    """Replace the first data.work_dir line, keeping everything else as-is."""
    pattern = re.compile(r"^(?P<indent>\s+)work_dir:.*$", re.MULTILINE)
    if not pattern.search(text):
        raise ValueError("Could not find a work_dir line in the source config.")
    # Single quotes: YAML keeps backslashes literal (Windows paths stay intact).
    safe = work_dir.replace("'", "''")
    return pattern.sub(lambda m: f"{m.group('indent')}work_dir: '{safe}'", text, count=1)


def main() -> int:
    parser = argparse.ArgumentParser(description="Make config_full_image.yml from config.yml.")
    parser.add_argument("--source", default="config.yml")
    parser.add_argument("--output", default="config_full_image.yml")
    parser.add_argument("--work-dir", default=r"C:\mouse_brain_work_full_image")
    args = parser.parse_args()

    source = Path(args.source)
    if not source.is_file():
        print(f"ERROR: source config not found: {source}", file=sys.stderr)
        return 2
    text = source.read_text(encoding="utf-8")
    out_text = HEADER + rewrite_work_dir(text, args.work_dir)
    Path(args.output).write_text(out_text, encoding="utf-8")
    print(f"Wrote {args.output} (work_dir={args.work_dir}); all other fields copied from {source}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
